### ISSUE TITLE
[BUG] Fix npm dev/build/start scripts

### ISSUE THREAD

**Issue by Arthelon** [GTBitsOfGood/bog-bot#15]
**Describe the bug**
npm scripts to build/run the project don't work at the moment. `next` CLI expects a `pages/` directory in the projects root.

**To Reproduce**
Checkout master and run one of the following npm commands:
- `dev`
- `build`
- `start`

**Screenshots**
![image](https://user-images.githubusercontent.com/11952174/83961608-52d6f980-a8c7-11ea-825f-177587c04a94.png)

**Additional context**
Beyond serverless API routes, I don't see any reason to use NextJS for a slackbot. Makes more sense to use a regular NodeJS server or some serverless slackbot framework.

**Comment by karpawich** [comment]
This is not a bug; the master branch is not intended to build on Vercel, for now.
