### ISSUE TITLE
Create a Member Mongoose schema with Role and Team support

### ISSUE THREAD

**Issue by karpawich** [GTBitsOfGood/bog-bot#2]
_This Issue relies on_ #1 _to be complete before it can be assigned._

**The feature**
Implement a `Member` Mongoose schema with support for Role and Team** functionality.

**Detailed explanation**
The `Member` Mongoose schema should include the following fields to start:
- First name (String)
- Last name (String)
- Role (String)
- Team (ObjectId)
- Bits (Number), default is 0

**Comment by Arthelon** [comment]
For roles, I think a simple enum of `members`, `leadership`, and `exec` will suffice. No need for departmental commands for now.
